




function showText(){
	
	const urlParams = new URLSearchParams(window.location.search);
  const valor = urlParams.get('text');
	const txth1 = document.getElementById("textH1")
	const txtP = document.getElementById("textP")
	const img = document.getElementById("imgId")
  if(valor == "MusicaTerapia"){
	  img.setAttribute('src', './assetsPet/DogMusic.png');
	  txtP.innerHTML = "1. Melhora do Humor: A música tem o poder de influenciar as emoções e o humor dos cães. Certos estilos musicais ou melodias suaves podem promover uma sensação de relaxamento e contentamento, melhorando o humor do animal. <br><br> 2. Redução dos Níveis de Ansiedade: A música calmante e relaxante pode ajudar a reduzir a ansiedade em cães, especialmente em situações estressantes, como durante tempestades, fogos de artifício ou visitas ao veterinário. <br><br> 3. Diminuição do Estresse: Sons harmoniosos podem contribuir para diminuir o estresse em cães, proporcionando um ambiente mais tranquilo e acolhedor para eles. <br><br> 4. Efeito da Música Clássica: Alguns estudos sugerem que a música clássica, em particular, tem o poder de diminuir a produção do hormônio cortisol, que está relacionado à condição de estresse. Assim, a música clássica pode ser especialmente benéfica para cães em momentos de agitação ou tensão. <br><br> 5. Reforço Positivo em Situações de Medo: A música pode ser utilizada como uma ferramenta de reforço positivo para ajudar cães a superar medos e fobias. Ao associar determinadas músicas com experiências agradáveis, o cão pode gradualmente mudar sua percepção negativa sobre situações temidas. <br><br> É importante destacar que cada cão pode ter preferências musicais individuais, e nem todas as músicas serão apropriadas ou benéficas para todos os animais (isso em caso de músicas desarmônicas). A seleção da música deve levar em consideração o temperamento e as necessidades específicas de cada cão. Além disso, a musicoterapia é uma abordagem complementar e não deve substituir tratamentos médicos ou comportamentais adequados. Portanto, é muito importante saber usar o estilo musical para cada necessidade. Somente usamos músicas harmônicas para proporcionar uma alteração positiva na mente e no corpo de nossos hospedes."
	  txth1.innerHTML = "Musicoterapia"
  }
  else if(valor == "Cromoterapia"){
	  img.setAttribute('src', './assetsPet/DogRainbow.png');
	  txtP.innerHTML = "1. Resgata o Estado Saudável dos Órgãos: Ao aplicar as cores específicas em áreas do corpo do cão onde ocorrem disfunções ou desequilíbrios, a cromoterapia visa estimular a restauração do bom funcionamento dos órgãos e sistemas, contribuindo para a saúde geral do animal. <br><br> 2. Repõe a Energia Vital: As cores podem influenciar o campo energético do cão, restabelecendo o fluxo de energia e promovendo uma sensação renovada de vitalidade e bem-estar.  <br><br> 3. Equilíbrio Emocional e Vital: Cada cor tem uma vibração energética única que pode influenciar o estado emocional do cão. A cromoterapia busca harmonizar as emoções, reduzindo o estresse e a ansiedade, e ajudando o cão a se sentir mais equilibrado emocionalmente. <br><br> 4. Melhora o Sistema Imunológico: A aplicação das cores certas pode estimular o sistema imunológico do cão, tornando-o mais resistente a doenças e infecções, e apoiando a capacidade natural do corpo de se curar. <br><br> 5. Alívio de Dores: Certas cores são conhecidas por suas propriedades analgésicas e anti-inflamatórias. A cromoterapia pode ajudar a reduzir as dores e o desconforto em cães que sofrem de condições dolorosas, como artrite ou lesões musculares. <br><br> 6. Melhora da Cicatrização: A cromoterapia pode ser aplicada para estimular a regeneração celular e promover uma cicatrização mais rápida de feridas e lesões cutâneas em cães. <br><br> É essencial ressaltar que a cromoterapia não deve substituir o tratamento médico tradicional, mas pode ser uma abordagem complementar valiosa para melhorar a saúde e o bem-estar do cão. Antes de iniciar qualquer terapia alternativa, é fundamental consultar um médico veterinário para obter um diagnóstico adequado e garantir que a cromoterapia seja segura e apropriada para o cão em questão."
	  txth1.innerHTML = "Cromoterapia"
  }
    else if(valor == "Grounding"){
	 img.setAttribute('src', './assetsPet/dogSpleep.png');
	txtP.innerHTML = "1. Alívio de Fadigas Crônicas: O grounding permite que o cão absorva elétrons livres da terra, o que pode ajudar a reduzir a fadiga crônica, promovendo uma sensação de bem-estar e vitalidade. <br><br> 2. Redução de Dores: O contato com a terra pode contribuir para a diminuição das dores musculares e articulares, proporcionando alívio e melhorando a mobilidade dos cães, especialmente aqueles que sofrem de condições como osteoartrite. <br><br> 3. Alívio de Ansiedade e Depressão: A prática de grounding tem sido associada à redução dos níveis de cortisol, o hormônio do estresse, o que pode auxiliar na diminuição da ansiedade e depressão em cães, proporcionando-lhes uma sensação de tranquilidade e serenidade. <br><br> 4. Melhora do Distúrbio do Sono: O grounding tem o potencial de regular os ritmos circadianos dos cães, promovendo uma melhora na qualidade do sono e ajudando na regularidade dos padrões de descanso. <br><br> 5. Fortalecimento do Sistema Imunológico: A troca de elétrons através do grounding pode contribuir para o fortalecimento do sistema imunológico dos cães, tornando-os mais resistentes a doenças e infecções. <br><br> 6. Redução de Inflamações: A prática de grounding tem sido associada à redução de processos inflamatórios, o que pode ser benéfico para cães que sofrem de condições inflamatórias crônicas. <br><br> Em resumo, o método grounding proporciona uma série de benefícios para os cães, melhorando sua qualidade de vida, promovendo bem-estar físico e emocional, e contribuindo para uma saúde geral mais equilibrada. No entanto, é importante consultar um médico veterinário antes de implementar qualquer nova prática terapêutica em seu cão, especialmente se ele tiver condições médicas pré-existentes."
	  txth1.innerHTML = "Método Grounding"
  }
    else if(valor == "Brincadeiras"){
	img.setAttribute('src', './assetsPet/brincadeiras.png');
	  txtP.innerHTML = "1. Foco no Comportamento Desejado: Em vez de punir o pet pelos comportamentos indesejados, o treinamento com reforço positivo concentra-se em incentivar e recompensar as ações desejadas. Dessa forma, o animal é motivado a repetir as ações corretas. <br><br> 2. Sensações ou Recompensas Agradáveis: As recompensas utilizadas no reforço positivo podem ser variadas e devem ser escolhidas de acordo com as preferências do pet. Exemplos de recompensas incluem petiscos, elogios verbais, carinho, brinquedos, e qualquer coisa que o animal perceba como agradável. <br><br> 3. Condicionamento Associativo: A técnica de reforço positivo se baseia no conceito de condicionamento clássico ou operante. Ao associar o comportamento desejado a uma consequência positiva, o animal aprende a antecipar a recompensa e, portanto, fica mais inclinado a repetir a ação que lhe trouxe a recompensa. <br><br> 4. Timing Adequado: A entrega da recompensa deve ser feita imediatamente após o pet realizar o comportamento desejado, para que ele estabeleça a conexão entre a ação e a recompensa de forma clara e eficiente.5. Reforço Contínuo e Gradual: Inicialmente, o reforço positivo pode ser aplicado de forma contínua, ou seja, o pet é recompensado a cada vez que executa o comportamento correto. Conforme o treinamento avança e o comportamento se torna mais consistente, o reforço pode ser gradualmente intercalado, mantendo a motivação do pet. <br><br> O reforço positivo é uma abordagem eficaz e ética de treinamento, que fortalece o vínculo entre o dono e o pet, promove uma relação de confiança e ajuda a estabelecer comportamentos desejados de forma mais harmoniosa e positiva. No entanto, é importante lembrar que cada animal é único, e o treinamento deve ser adaptado às suas necessidades e características individuais para obter os melhores resultados. Buscar a orientação de um profissional de treinamento ou adestramento pode ser extremamente útil para garantir um treinamento adequado e bem-sucedido."
	  txth1.innerHTML = "Brincadeiras"
  }
}

showText()

